export const ENV = {
  APPWRITE_ENDPOINT: 'https://cloud.appwrite.io/v1',
  APPWRITE_PROJECT_ID: process.env.EXPO_PUBLIC_APPWRITE_PROJECT_ID!,
  DATABASE_ID: process.env.EXPO_PUBLIC_APPWRITE_DATABASE_ID!,
  USER_COLLECTION_ID: process.env.EXPO_PUBLIC_APPWRITE_COLLECTION_ID!,
  CHAT_ROOMS_COLLECTION_ID: process.env.EXPO_PUBLIC_APPWRITE_CHAT_ROOMS_COLLECTION_ID!,
  MESSAGES_COLLECTION_ID: process.env.EXPO_PUBLIC_APPWRITE_MESSAGES_COLLECTION_ID!,
};